### PR TITLE
Localization

### LINKED ISSUE #1: Explore Dart localization
Explore options for localization in Dart on both AngularDart & Flutter.

### LINKED ISSUE #48: Make i18n how to file
Just make internationalization tutorial, so everyone will know what files are related to that and how to translate stuff...

### PR DESCRIPTION
**Pull request by Kenny11CZ**
Fixes #1.
Fixes #48.

Added full i18n support.

We should specify where to store `.arb` files. Will web application have same strings as mobile? Because if not it's unnecessary to make it shared, since it would slowed down both of them. But if they will have atleast, let's say, 70% in common, then we should store them outside of both projects.

### CODE REVIEW

**Comment by Kenny11CZ** [comment]
It looks like it fails on pub get, again...

**Comment by Kenny11CZ** [comment]
According to your question (@tenhobi ) "How to localize AngularDart?", I think the same way we localize Flutter, since Flutter use [Intl](https://pub.dartlang.org/packages/intl) and [Intl_translation](https://pub.dartlang.org/packages/intl_translation) dart packages.

**Comment by Kenny11CZ** [comment]
I would make new folder, something like resources in project root, where we could store localization files, shared images, fonts, etc, so the logic contains only logic, not static resources. We have to store arb files, other files can be generated using some commands, but I think it's better to have it there, ready to go. Maybe later when we will create some sort of first-time initialization script

**Comment by tenhobi** [comment]
I think you cannot have things outside of your project. And the logic project has a purpose for storing common stuff, so why not to use it. :-) 

Keep it simple. s*.

**Comment by tenhobi** [comment]
We can rename the logic project as common, if it helps. 🗡

**Comment by tenhobi** [comment]
Please, @Kenny11CZ, remove all generated data from the project and write down how to set up and work with translations. :-)

**Comment by tenhobi** [comment]
Merge #57 inside, so you have the stuff updated.

**Comment by Kenny11CZ** [comment]
Should work for Flutter but i can't test it since "fixed" dependencies don't work for me, for some reason.

**Comment by tenhobi** [comment]
Hmm, run the `flutter channel master`, update Flutter and Darth and we will figure out the dependencies later. Btw. try to use `flutter packages get`. For some reason I think it works better and don't throw errors when `pub get` does.

**Comment by tenhobi** [comment]
I still don't understand, from the md you have done, how to set up both Czech & English translations and why I need those generated .arb files.

**Comment by Kenny11CZ** [comment]
Okey, I will try that ASAP.

Why we need `.arb` files like in repo or overall? `.arb` files contains translations itself, all `.dart` files generated with it are just some kind of wrappers generated from these `.arb` files. It's like JSON, but better (for this purpose). As you can see in reference for (Intl)[https://pub.dartlang.org/packages/intl] library, these localized strings supports variables, plurals and all that fancy stuff and `.arb` file format is capable of storing it.

**Pull request merged**
